//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multifenetrage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmPays
    {
        public int Id { get; set; }
        public Nullable<int> IdFilm { get; set; }
        public Nullable<int> IdPays { get; set; }
        public string Info { get; set; }
        public Nullable<System.DateTime> DateTournage { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual PAYS PAYS { get; set; }
    }
}
